/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  MockMinimalErc721,
  MockMinimalErc721Interface,
} from "../MockMinimalErc721";

const _abi = [
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "setOwner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class MockMinimalErc721__factory {
  static readonly abi = _abi;
  static createInterface(): MockMinimalErc721Interface {
    return new utils.Interface(_abi) as MockMinimalErc721Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockMinimalErc721 {
    return new Contract(address, _abi, signerOrProvider) as MockMinimalErc721;
  }
}
